 steps:
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/financial_portfolio_calculator:latest .']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/financial_portfolio_calculator:latest']
   secretEnv: ['USERNAME']
 availableSecrets:
   secretManager:
   - versionName: projects/project02-306218/secrets/docker-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/project02-306218/secrets/docker-username/versions/1
     env: 'USERNAME'
